source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'QuickTalk' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking', '3.1.0'
  pod 'SDWebImage', '4.0.0'
  pod 'YYModel', '1.0.4'
  pod 'YYCache', '1.0.4'
  pod 'YYText', '1.0.7'
  pod 'KVOController', '1.2.0'
  pod 'Aspects', '1.4.1'
  pod 'MLeaksFinder', '0.2.1'
  pod 'Masonry', '1.0.2'
  pod 'DZNEmptyDataSet', '1.8.1'
  pod 'TSMessages', '0.9.12'
  pod 'MBProgressHUD', '1.0.0'
  pod 'MMPopupView', '1.7.2'
  pod 'MJRefresh', '3.1.12'
  pod 'Toast', '3.1.0'
  pod 'SAMKeychain', '1.5.2'
  pod 'QBPopupMenu'
  pod 'HMSegmentedControl', '1.5.4'

  pod 'RBScheduler', :git => 'https://github.com/zruibin/RBScheduler.git', :tag => '2.0.2'
  
  #第三方服务
  pod 'Bugly'
  pod 'SMSSDK'

  target 'QuickTalkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickTalkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
